include theos/makefiles/common.mk

BUNDLE_NAME = ncwundergroundprefs
ncwundergroundprefs_FILES = ncwundergroundprefs.m
ncwundergroundprefs_INSTALL_PATH = /Library/WeeLoader/Plugins/ammNCWunderground.bundle/
ncwundergroundprefs_FRAMEWORKS = UIKit
ncwundergroundprefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
